### PR TITLE
Few menu changes

### PR DESCRIPTION
**Pull request by PossiblyCharles**
Added some config colour options and implemented them.

Also added button hover to player select buttons.

### CODE REVIEW

**Comment by PossiblyCharles** [comment]
image

**Review by Pdzly — APPROVED** [review]

**Review by Pdzly — CHANGES_REQUESTED** [review]
Where is resource.addfile? because it will create an error if this is addon is not localy installed or not from workshop installed. and why do this X button be a png ? it has basic colors and is nothing special that it needs to be a picture

**Comment by PossiblyCharles** [comment]
All addons should be installed through workshop for client. Using fastDL is craaaaazy slow due to source limitations.

Once it's on workshop we should use https://wiki.facepunch.com/gmod/resource.AddWorkshop as the workshop downloads happen using the steam client and are much MUCH faster.

+ servers should really make resource packs and have clients auto download them with workshop as it's faster to be one big download than multiple small 1 by 1.

**Comment by Pdzly** [comment]
But if you want it install over legacy. Fastdl shouldnt be used yeah, but sometimes someone wants to install it as legacy addon. and if a freaking (X) close button is an error material 

The bigest part is, that we have it on github, so we ENCOURAGE usage of legacy addon installation + many config settings are only avaible on files

**Comment by PossiblyCharles** [comment]
As the addon would be calling [resource.AddWorkshop](https://wiki.facepunch.com/gmod/resource.AddWorkshop) their clients would download through workshop anyway. No matter how the addon's installed on the server, the clients would be downloading through workshop.

**Comment by Pdzly** [comment]
It will create some incompatibilities if legacy and workshop addon is installed. If someone installs it legacy + changes something clientside. Yeah its getting probably overwritten

**Comment by PossiblyCharles** [comment]
Clientside lua is still sent the usual way. Client workshop downloads on join do not load lua.

(Unless something changed since I last touched gmod, but I doubt it. That would be a silly change.)

**Comment by Pdzly** [comment]
> Clientside lua is still sent the usual way. Client workshop downloads on join do not load lua.
> 
> (Unless something changed since I last touched gmod, but I doubt it. That would be a silly change.)

Okay if you say so :). We need to add there resource.addworkshop when we publish it to workshop. 

In the other hand why should the lua AND the material be send again to the server ( even if its not executed ). And if its a steam workshop addon it wont send the file to the user it sends the whole addon. I would still recomend resource.AddFile for not sending clients 2x the same data

**Pull request merged**
