### PR TITLE
Fixed it with the request. We need to test it ;)

### PR DESCRIPTION
**Pull request by Pdzly**

### CODE REVIEW

**Review by beanbash — DISMISSED** [review]
Currently I get this error below when I attempt to /accepttransfer.

This must be fixed before merging, I'll look into it and see what I can do on my part.

```
[gmodtransfer] addons/gmodtransfer/lua/autorun/server/sv_hedgetransfer.lua:218: attempt to perform arithmetic on global 'requestAmount' (a nil value)

  1. HandleRequest - addons/gmodtransfer/lua/autorun/server/sv_hedgetransfer.lua:218

   2. f - addons/gmodtransfer/lua/autorun/server/sv_hedgetransfer.lua:268
```

**Comment by Pdzly** [comment]
yeah my bad its an easy fix but until later i will fix it

**Comment by Pdzly** [comment]
You dont have the newest version ;( On my version it will function @hedges7

**Comment by beanbash** [comment]
> You dont have the newest version ;( On my version it will function @hedges7 
> 

Maybe not I guess. Go ahead and merge it if it works.

**Comment by Pdzly** [comment]
It should work XD

**Pull request merged**
